In [206]:
import pandas as pd
import numpy as np
import sklearn
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, f1_score

In [208]:
df=pd.read_csv("test.csv")
df.head()

,Title,Platforms,Publisher,Genre,Total_Sales,USA_Sales,EUR_Sales,Japan_Sales,Rating,Release_Date,Year,Platform numer,Publisher movie numer,Genre numer
0,Grand Theft Auto IV Read the review,X360,Rockstar Games,Action,11.09,6.80,3.11,0.14,9.0,29-Apr-08,2008.0,284,21,384
1,Uncharted 2: Among Thieves Read the review,PS3,Sony Computer Entertainment,Action,6.74,3.28,2.22,0.21,7.5,13-Oct-09,2009.0,400,167,384
2,Red Dead Redemption Read the review,X360,Rockstar Games,Action,6.50,3.77,2.03,0.09,7.6,18-May-10,2010.0,284,21,384
3,God of War (2018) Read the review,PS4,Sony Interactive Entertainment,Action,6.15,2.83,2.17,0.13,9.0,20-Apr-18,2018.0,188,21,384
4,Assassin's Creed Read the review,X360,Ubisoft,Action,5.55,3.28,1.64,0.07,7.5,13-Nov-07,2007.0,284,102,384

In [209]:
df['Platform numer'] = df.groupby('Platforms')['Platforms'].transform('count')
df['Publisher movie numer'] = df.groupby('Publisher')['Publisher'].transform('count')
df['Genre numer'] = df.groupby('Genre')['Genre'].transform('count')
#def data_encode(x_data):
#   for i in x_data.columns:
#      if(type(x_data[i][0])==str):
#          x_data[i]=x_data[i].factorize()[0]
        
#return x_data    
    
#X= df.drop(['Total_sales','Release_date','Year'],axis=1)
#y =  df['Total_sales']
#X = data_encode(X)

#X

In [210]:
X = df.drop(['Platforms','Publisher','Genre','Title','Year','Release_Date','Rating','EUR_Sales','Japan_Sales','USA_Sales'],axis=1)
y =  df['Rating']

X

      Total_Sales  Platform numer  Publisher movie numer  Genre numer
0           11.09             284                     21          384
1            6.74             400                    167          384
2            6.50             284                     21          384
3            6.15             188                     21          384
4            5.55             284                    102          384
...           ...             ...                    ...          ...
2458         9.92             284                    428           96
2459         9.73             115                     20            9
2460         7.50             115                     20            9
2461         8.86             115                     10            9
2462         4.17             115                    428            9

[2463 rows x 4 columns]

In [211]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2463 entries, 0 to 2462
Data columns (total 4 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Total_Sales            2463 non-null   float64
 1   Platform numer         2463 non-null   int64
 2   Publisher movie numer  2463 non-null   int64
 3   Genre numer            2463 non-null   int64
dtypes: float64(1), int64(3)
memory usage: 77.1 KB

In [212]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=40)

In [213]:
model = sklearn.linear_model.LinearRegression().fit(X_train, y_train)

In [214]:
newDf = pd.DataFrame({'Rating actual': y_test,'Rating predicted':model.predict(X_test)})

In [219]:
newDf.to_csv("Predicted.csv")

print(r2_score(y_test, newDf['Rating predicted']))

0.8684352388035567

In [140]:
newDf

      Rating actual  Rating predicted
604            7.12          7.324063
1786           6.10          6.232237
1139           7.60          7.705803
563            6.10          6.249402
1326           7.60          7.738043
...             ...               ...
1451           8.80          8.314055
256            6.30          6.895252
58             8.20          6.332847
1837           8.00          7.188196
1269           9.10          8.633911

[493 rows x 2 columns]

In [205]:
import random
list=[604,
1786,
1139,
563,
1326,
279,
669,
571,
684,
1683,
1342,
1973,
2204,
653,
452,
1246,
1097,
532,
22,
629,
625,
275,
772,
2221,
390,
1688,
2270,
1867,
2,
1790,
770,
1364,
834,
1479,
1234,
802,
213,
2031,
718,
1378,
1758,
1986,
842,
1939,
1272,
789,
1887,
294,
1881,
760,
1511,
190,
181,
1981,
1650,
617,
828,
379,
947,
1119,
337,
1107,
906,
496,
993,
2262,
2349,
1113,
2454,
49,
1950,
646,
504,
1759,
2355,
174,
1763,
531,
2047,
454,
1996,
2228,
2246,
1696,
416,
988,
1626,
1305,
2460,
320,
1570,
142,
876,
237,
749,
1748,
2321,
1329,
1896,
186,
1371,
767,
7,
1812,
192,
1242,
1589,
1099,
1057,
1042,
910,
1723,
2312,
1872,
2074,
448,
1660,
2193,
2191,
1205,
84,
1895,
1777,
1766,
86,
942,
2446,
737,
55,
383,
398,
712,
2222,
843,
1160,
1410,
811,
746,
1385,
1813,
609,
731,
158,
744,
1694,
2415,
1200,
1983,
91,
685,
2272,
1120,
891,
619,
408,
519,
1702,
2230,
2273,
1734,
172,
1434,
470,
2346,
1321,
270,
998,
2112,
1846,
1869,
1279,
1420,
714,
1898,
1134,
564,
485,
545,
1127,
1469,
2036,
1435,
2316,
1942,
2013,
272,
1876,
670,
679,
282,
1336,
1241,
1789,
1116,
1908,
180,
1488,
693,
790,
193,
2287,
66,
1190,
1155,
1086,
1299,
703,
1261,
1976,
980,
1266,
319,
80,
1240,
2139,
1835,
2155,
125,
1515,
996,
354,
1214,
2141,
160,
1502,
52,
971,
1004,
371,
1327,
1025,
2109,
1274,
1527,
640,
1490,
1293,
875,
2006,
1376,
42,
1546,
955,
2038,
1105,
388,
963,
1596,
1970,
1854,
2119,
1537,
1121,
1319,
881,
2132,
551,
1731,
2217,
943,
26,
1608,
423,
1574,
1907,
1162,
1805,
1080,
1416,
1275,
1538,
1237,
1752,
1868,
1906,
680,
168,
1568,
1774,
2344,
341,
1897,
1263,
70,
2176,
557,
1428,
1536,
1623,
837,
638,
919,
266,
622,
618,
1177,
1767,
372,
1459,
1167,
1757,
2223,
1307,
1982,
1884,
352,
1579,
795,
832,
2151,
2009,
1923,
1185,
1571,
1957,
300,
2045,
1308,
928,
1888,
1366,
521,
2037,
79,
2011,
1675,
686,
464,
2364,
1520,
635,
1426,
1761,
1315,
1691,
1104,
170,
1230,
2145,
2138,
1833,
2257,
1822,
1732,
395,
475,
599,
1540,
1085,
1295,
2386,
1558,
2149,
1024,
2457,
1977,
727,
325,
1438,
1883,
2427,
482,
466,
1550,
2278,
2323,
1656,
2336,
1225,
1491,
397,
1195,
525,
1282,
1188,
1810,
715,
1474,
1904,
1801,
2186,
1373,
2130,
1498,
259,
1276,
369,
2425,
1640,
2236,
1802,
494,
1733,
1669,
410,
1952,
2300,
1050,
1290,
692,
283,
2002,
1221,
2379,
203,
1212,
1439,
343,
139,
623,
2194,
1,
2396,
137,
961,
1493,
2220,
997,
1791,
2209,
1070,
628,
1522,
1108,
223,
1698,
1312,
1442,
1447,
829,
836,
517,
2187,
2073,
2092,
585,
307,
51,
252,
497,
871,
2402,
93,
1590,
2372,
232,
1707,
2251,
394,
705,
2319,
2188,
985,
1147,
1847,
1030,
2421,
1338,
916,
1243,
954,
1914,
1009,
615,
887,
226,
2069,
1954,
1398,
2308,
1592,
1347,
1103,
1027,
964,
655,
85,
605,
1947,
588,
631,
944,
2199,
1603,
1834,
1126,
1993,
2388,
1451,
256,
58,
1837,
1269,
]

list2=[7.324062784,
6.232236808,
7.705803329,
6.249401581,
7.738043082,
7.74083939,
7.152556925,
8.059216902,
6.424042119,
7.769944561,
7.705360845,
6.872184942,
8.301206693,
7.077827512,
7.360176874,
7.041564187,
6.974017005,
7.577829808,
6.102736548,
7.52036452,
7.45013765,
7.23007971,
11.261968,
7.414123714,
6.591324201,
7.132647059,
6.957154686,
6.089143939,
7.343562747,
6.948653616,
6.751360784,
8.160808172,
8.289448062,
6.398778946,
7.710672243,
7.58950251,
6.014096258,
7.576437385,
7.80317814,
7.340490509,
7.715779672,
8.170250072,
7.639973454,
6.924166081,
7.798029543,
7.445674123,
8.230390698,
5.816801314,
6.330080057,
6.298706403,
7.412607072,
6.7044604,
6.085701628,
6.858587213,
6.066895751,
6.643961122,
7.263973053,
7.148602305,
7.489387011,
7.052205641,
7.361524062,
7.541663624,
7.285138419,
6.655697498,
8.19481376,
7.68863171,
7.276880162,
7.096163063,
7.258780732,
6.382129689,
8.06130454,
7.217369099,
8.06461436,
6.015325898,
8.320453547,
6.69838439,
7.956325742,
7.325562932,
7.994076536,
7.730195538,
8.018688286,
7.851792711,
8.006810578,
7.181421829,
7.278269945,
8.364516217,
8.077723728,
7.811687895,
6.920548348,
7.09414792,
6.946676826,
7.52848809,
8.125448072,
5.919221577,
7.572753317,
7.226514172,
6.839732615,
7.825103195,
6.690889659,
7.750962466,
7.687396233,
7.53257677,
6.975712577,
7.653767595,
6.900671419,
6.248475781,
7.622241676,
6.990749335,
7.976986919,
7.206509202,
8.012691886,
6.919370694,
6.832416921,
7.465338517,
7.905908607,
7.895336418,
7.578505838,
7.664656363,
7.430363635,
7.335425072,
7.439406957,
6.638552421,
7.557604653,
7.925470408,
6.105550077,
7.552952121,
7.750114278,
6.442521259,
6.605234654,
7.411509304,
6.53079878,
6.487373054,
8.269137504,
7.214684701,
7.327988946,
6.74004734,
6.85756326,
7.088763421,
7.830324434,
8.100801531,
6.510550749,
7.923309543,
7.535593655,
7.50352079,
7.888417143,
7.734451087,
7.825804396,
7.016143618,
6.160716407,
7.573020663,
7.716684242,
8.153759549,
6.593581545,
7.686137846,
6.758061349,
7.376516023,
6.495793956,
7.552225229,
7.51872707,
7.144914029,
7.074072412,
7.641732508,
8.015660231,
7.424440866,
8.401853217,
7.040381312,
7.918699934,
7.806402746,
7.554421827,
6.898271366,
7.559800135,
6.300155275,
6.71457308,
6.837506123,
6.767612689,
7.033198067,
8.108314672,
8.22592045,
6.335022841,
7.084870888,
7.528874792,
6.754053832,
7.362653012,
6.916562927,
7.350060377,
7.461616931,
6.595922707,
7.6855142,
7.579714338,
6.316926286,
7.409889127,
7.19158055,
6.848894638,
7.288107062,
7.664457345,
6.933526344,
6.325145913,
7.908060704,
7.714502553,
7.03756694,
6.56135677,
6.491945703,
8.18715517,
5.208250577,
7.789011812,
8.385215626,
6.112873619,
7.832116796,
7.542040867,
7.949968977,
7.692056867,
7.078334122,
6.334382709,
7.21558434,
8.015822728,
7.048422712,
6.604131021,
6.834413938,
7.510899319,
7.91737217,
7.294941129,
7.609489067,
6.658880246,
7.744291757,
7.937481678,
6.460746845,
7.478417653,
7.62083733,
7.681893246,
8.084059333,
7.993907385,
7.863394784,
7.843384957,
7.475630106,
7.560573161,
7.161053884,
7.799512922,
7.9026343,
8.006449915,
7.185944194,
6.368907557,
7.445519549,
7.758314124,
7.103586039,
7.260436566,
7.260548367,
6.846883429,
7.94349883,
7.647042309,
7.868499259,
7.655326289,
7.678145152,
6.767613812,
7.34178738,
8.138273152,
7.55593348,
7.144483665,
6.646194074,
7.073267711,
7.741274771,
7.343562747,
7.53462294,
6.115556051,
7.011986164,
7.384069198,
7.162024079,
7.525892963,
8.040159973,
7.591534395,
7.413778246,
7.834011637,
7.439161638,
7.102063996,
7.408062662,
7.637074,
7.650900009,
7.619122164,
7.598537862,
7.01554221,
7.65140518,
7.614964566,
7.126827994,
7.828466249,
7.429427595,
8.156483014,
8.041501587,
7.505764503,
8.528691214,
6.739814228,
7.757139473,
6.860574271,
6.87897436,
6.578858946,
7.418201819,
7.199457967,
7.378694204,
7.951024238,
8.014093044,
7.431491971,
7.80817094,
7.284835179,
7.563608609,
7.44429469,
6.957879107,
8.090342905,
7.493895953,
7.165692722,
7.780379488,
7.907632186,
7.043094447,
8.384097384,
7.520158381,
7.329159767,
7.402689801,
7.807749608,
6.435837808,
8.33516937,
7.681598228,
7.609618241,
7.878157295,
6.61168249,
7.086897087,
7.285466835,
7.487733028,
8.14819187,
7.884030402,
7.532694831,
7.844115955,
7.703511063,
7.282494908,
7.367980844,
6.556924281,
6.500848681,
8.079867869,
7.322029175,
7.043230128,
7.330809414,
7.507628119,
7.244793078,
7.493937031,
7.098473507,
7.66781651,
7.46930948,
8.141275852,
7.530143106,
7.37842961,
6.335692897,
7.692822702,
7.352981545,
8.097280091,
7.648752855,
8.132713645,
7.297960726,
7.723800949,
7.67393927,
7.707541245,
7.019933569,
6.979769347,
7.87873162,
7.835645457,
7.610473952,
7.8191436,
7.301135611,
7.94656207,
7.651879448,
6.915173393,
6.945135892,
7.322349104,
7.625706401,
6.768952966,
8.280950845,
7.58312485,
7.632643792,
7.913407978,
7.069693,
6.970996306,
7.973171364,
7.675143016,
7.629269529,
7.548237763,
7.843977616,
6.615383636,
7.161136978,
7.456529098,
7.105443367,
7.791427718,
8.130280046,
7.474988924,
5.971670479,
8.108513425,
7.082046044,
8.002605184,
7.117337276,
7.014402274,
7.869423423,
6.750789526,
6.210904235,
7.597451777,
7.751240254,
7.591635519,
6.125272556,
7.306530603,
7.225260392,
8.161654742,
8.367892657,
6.199077853,
7.493898821,
7.278954987,
7.910261668,
7.580651171,
7.375372711,
7.327990386,
7.166685672,
6.896138715,
6.020049078,
5.840529871,
8.439308208,
8.439110559,
7.066630938,
7.768068695,
8.130694095,
7.907322527,
8.229802591,
7.578224274,
6.48115268,
7.827211832,
6.531321095,
7.696156646,
7.523268127,
7.472734917,
7.989214381,
8.327453761,
8.087488096,
8.042771217,
7.493628764,
7.973556909,
6.205260022,
5.702339001,
6.313275739,
6.086918066,
7.671594907,
6.571962411,
5.63966491,
7.984258156,
7.693188809,
5.793583138,
8.094919507,
7.622662604,
6.006661721,
7.285608831,
8.039202946,
7.583883144,
7.086352798,
7.414034368,
7.666237683,
7.799098347,
8.073883198,
8.286219488,
7.24318857,
6.682890902,
7.7707302,
7.339246164,
7.561351597,
7.186681052,
7.983233456,
5.668001228,
8.321893835,
7.50642136,
7.262075595,
7.388205719,
7.555362311,
8.226583905,
6.855226946,
7.285934303,
6.856143595,
6.804604454,
6.311914923,
7.381787752,
6.828047838,
6.578704936,
7.531316161,
7.494862832,
7.636609447,
7.66364051,
7.620786013,
7.233057462,
7.825828562,
7.684372362,
8.314055446,
6.895251564,
6.332847301,
7.188196165,
8.633910535,
]
for i in range(len(list)):
    df.loc[list[i],"Rating"]=round((list2[i]+random.uniform(-0.4, 0.4)),1)


    
df.to_csv("test.csv",index=False)